offutils.py: fix type mismatch.
When trying to assess whether offpunk would have a hard dependency on
the less command, I noticed that trying to execute offpunk without
less results in:

	$ offpunk --version
	Traceback (most recent call last):
	  File "/usr/bin/offpunk", line 5, in <module>
	    from offpunk import main
	  File "/usr/lib/python3.13/dist-packages/offpunk.py", line 21, in <module>
	    import ansicat
	  File "/usr/lib/python3.13/dist-packages/ansicat.py", line 15, in <module>
	    import netcache
	  File "/usr/lib/python3.13/dist-packages/netcache.py", line 19, in <module>
	    import offutils
	  File "/usr/lib/python3.13/dist-packages/offutils.py", line 115, in <module>
	    if not shutil.which(CMDS["less"]):
	           ~~~~~~~~~~~~^^^^^^^^^^^^^^
	  File "/usr/lib/python3.13/shutil.py", line 1518, in which
	    dirname, cmd = os.path.split(cmd)
	                   ~~~~~~~~~~~~~^^^^^
	  File "<frozen posixpath>", line 103, in split
	TypeError: expected str, bytes or os.PathLike object, not NoneType

Ensuring that CMDS["less"] is of type "str" at all time resolves the
mismatch.  Also, the empty string will be recognised as False by logic
handled by the "not" keyword, so the change should not interfere with
the rest of the logic of the program.  This also reveals the easter
egg.  :)

Signed-off-by: Étienne Mollier <emollier@debian.org>